### ISSUE TITLE
the calculated value is not between 0-1

### ISSUE THREAD

**Issue by XinghaiLiao** [ykumards/simtorch#20]
I have used your code to calculate CKA matrices,，but the calculated value is not between 0-1.Any help would be great. Thanks!

**Comment by anushiya1** [comment]
Hi, may I check if this is solved? Thanks!

**Comment by humblef-oo-l** [comment]
Nah! This is for both cka & deltacka

**Comment by ykumards** [comment]
Hello! Please check #52 and let me know if this fixes your issue
